//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvUIB-R.xml)
            
     Last generated: 13-09-2004  19:35:14 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvUIBC5R.res");
USEUNIT("..\..\run\JvUIBMetaData.pas");
USEUNIT("..\..\run\JvUIBSQLParser.pas");
USEUNIT("..\..\run\JvUIB.pas");
USEUNIT("..\..\run\JvUIBase.pas");
USEUNIT("..\..\run\JvUIBConst.pas");
USEUNIT("..\..\run\JvUIBError.pas");
USEUNIT("..\..\run\JvUIBLib.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("CJCL50.bpi");
USEPACKAGE("vcl50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

