object Form1: TForm1
  Left = 197
  Top = 107
  Width = 783
  Height = 540
  Caption = 'Form1'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 448
    Width = 775
    Height = 65
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    object Label1: TLabel
      Left = 16
      Top = 8
      Width = 43
      Height = 13
      Caption = 'Columns:'
    end
    object Label2: TLabel
      Left = 176
      Top = 8
      Width = 31
      Height = 13
      Caption = 'Count:'
    end
    object tbCols: TTrackBar
      Left = 16
      Top = 24
      Width = 150
      Height = 45
      Max = 100
      Min = 1
      Orientation = trHorizontal
      ParentShowHint = False
      Frequency = 10
      Position = 1
      SelEnd = 0
      SelStart = 0
      ShowHint = True
      TabOrder = 0
      ThumbLength = 15
      TickMarks = tmBottomRight
      TickStyle = tsAuto
      OnChange = tbColsChange
    end
    object tbCount: TTrackBar
      Left = 168
      Top = 24
      Width = 150
      Height = 45
      Max = 1000
      Min = 1
      Orientation = trHorizontal
      ParentShowHint = False
      Frequency = 100
      Position = 1
      SelEnd = 0
      SelStart = 0
      ShowHint = True
      TabOrder = 1
      ThumbLength = 15
      TickMarks = tmBottomRight
      TickStyle = tsAuto
      OnChange = tbCountChange
    end
    object AutoScroll: TCheckBox
      Left = 368
      Top = 24
      Width = 97
      Height = 17
      Caption = 'AutoScroll'
      Checked = True
      State = cbChecked
      TabOrder = 2
      OnClick = AutoScrollClick
    end
  end
end
