JEDI-VCL provides you with various components suitable for timing and scheduling tasks. The
following components are provided:

<TABLE>
  Component                       Description
  ---------                       -----------
  TJvAlarms                       A programmable timer that can handle recurring tasks. Tasks can be
                                    scheduled to recur using various intervals.
</TABLE>