program DtxTool;

uses
  Forms,
  MainFrm in 'MainFrm.pas' {FormMain},
  Core in '..\..\..\JVCL\install\JVCLInstall\Core.pas',
  HtHint in '..\..\..\JVCL\install\JVCLInstall\Helpers\HtHint.pas',
  PageBuilder in 'PageBuilder.pas',
  HelpBuild in 'HelpBuild.pas',
  PgConfig in 'Pages\PgConfig.pas',
  PgSummary in 'Pages\PgSummary.pas',
  FrmConfigPage in 'Frames\FrmConfigPage.pas' {FrameConfigPage: TFrame},
  HelpBuildData in 'HelpBuildData.pas',
  PgBuild in 'Pages\PgBuild.pas',
  FrmBuild in 'Frames\FrmBuild.pas' {FrameBuild: TFrame},
  DtxParser in '..\Common\DtxParser.pas',
  DtxPasCombiner in '..\Common\DtxPasCombiner.pas',
  GroupDtxProducer in '..\Common\GroupDtxProducer.pas',
  JVCLHelpUtils in '..\Common\JVCLHelpUtils.pas',
  RegisteredClassesProducer in '..\Common\RegisteredClassesProducer.pas',
  PackageListProducer in '..\Common\PackageListProducer.pas',
  PasFilesStripper in '..\Common\PasFilesStripper.pas',
  AdjVclClxCvt in '..\Common\AdjVclClxCvt.pas',
  VclClxCvtUtils in '..\..\..\JVCL\devtools\JvclVclClx\VclClxCvtUtils.pas',
  dpp_PascalParser in '..\..\..\JVCL\devtools\dpp32\dpp_PascalParser.pas',
  DelphiParser in '..\GenDtx\DelphiParser.pas',
  DelphiParserUtils in '..\GenDtx\DelphiParserUtils.pas',
  DoxProducer in '..\Common\DoxProducer.pas',
  ImagesProducer in '..\Common\ImagesProducer.pas',
  pngimage in '..\GenImages\pngimage.pas',
  pngzlib in '..\GenImages\pngzlib.pas',
  pnglang in '..\GenImages\pnglang.pas',
  DtxAnalyzer in '..\Common\DtxAnalyzer.pas',
  DirCleaner in '..\Common\DirCleaner.pas',
  Utils in '..\..\..\JVCL\devtools\JvclVclClx\Utils.pas',
  PackageDtxProducer in '..\Common\PackageDtxProducer.pas',
  WinHelpPostProcessor in '..\Common\WinHelpPostProcessor.pas',
  FrmBuildOptions in 'Frames\FrmBuildOptions.pas' {FrameBuildOptions: TFrame},
  PgBuildOptions in 'Pages\PgBuildOptions.pas',
  HtmlHelpPostProcessor in '..\Common\HtmlHelpPostProcessor.pas',
  HtmlHelpCompiler in '..\Common\HtmlHelpCompiler.pas',
  FrmPostBuildOptions in 'Frames\FrmPostBuildOptions.pas' {FramePostBuildOptions: TFrame},
  PgPostBuildOptions in 'Pages\PgPostBuildOptions.pas',
  WinHelpCompiler in '..\Common\WinHelpCompiler.pas',
  ParserTypes in '..\GenDtx\ParserTypes.pas',
  ZipExec in '..\Common\ZipExec.pas',
  UnzipExec in '..\Common\UnzipExec.pas',
  FrmUnzipOptions in 'Frames\FrmUnzipOptions.pas' {FrameUnzipOptions: TFrame},
  FrmZipOptions in 'Frames\FrmZipOptions.pas' {FrameZipOptions: TFrame},
  PgUnzipOptions in 'Pages\PgUnzipOptions.pas',
  PgZipOptions in 'Pages\PgZipOptions.pas',
  DtxDiagnoser in '..\Common\DtxDiagnoser.pas',
  FrmDiagnoseOptions in 'Frames\FrmDiagnoseOptions.pas' {FrameDiagnoseOptions: TFrame},
  PgDiagnoseOptions in 'Pages\PgDiagnoseOptions.pas',
  DuplicateIdentifiersProducer in '..\Common\DuplicateIdentifiersProducer.pas',
  InvalidWordsProducer in '..\Common\InvalidWordsProducer.pas',
  Settings in '..\GenDtx\Settings.pas',
  DtxFilesPreProcessor in '..\Common\DtxFilesPreProcessor.pas',
  DoxFileBuilder in '..\Common\DoxFileBuilder.pas',
  FrmDoxCompileOptions in 'Frames\FrmDoxCompileOptions.pas' {FrameDoxCompileOptions: TFrame},
  PgDoxCompileOptions in 'Pages\PgDoxCompileOptions.pas',
  HelpBuildHelper in 'HelpBuildHelper.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
