//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvAppFrm-D.xml)
            
     Last generated: 29-11-2003  13:54:58 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvAppFrmC5D.res");
USEUNIT("..\..\design\JvGradientCaptionForm.pas");
USEUNIT("..\..\design\JvAppFrmReg.pas");
USEUNIT("..\..\design\JvFormWallpaperEditor.pas");
USEUNIT("..\..\run\JvWallpaperEditForm.pas");
USEPACKAGE("JvAppFrmC5R.bpi");
USEPACKAGE("JvStdCtrlsC5R.bpi");
USEPACKAGE("CJCL50.bpi");
USEPACKAGE("CJCLVCL50.bpi");
USEPACKAGE("vcl50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

