//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvBands-D.xml)
            
     Last generated: 22-11-2003  06:09:54 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvBandsC5D.res");
USEUNIT("..\..\design\JvBandsReg.pas");
USEUNIT("..\..\design\JvBandObjectDLLWizard.pas");
USEUNIT("..\..\design\JvBandObjectDLLWizardForm.pas");
USEPACKAGE("JvBandsC5R.bpi");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JvCoreC5D.bpi");
USEPACKAGE("JvCustomC5R.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("CJCL50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

