//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvPrintPreview-D.xml)
            
     Last generated: 16-12-2003  23:14:26 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvPrintPreviewC5D.res");
USEUNIT("..\..\design\JvPreviewReg.pas");
USEPACKAGE("JvCoreC5D.bpi");
USEPACKAGE("JvPrintPreviewC5R.bpi");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("CJCL50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

