//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvCore-D.xml)
            
     Last generated: 28-04-2004  13:03:51 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvCoreC5D.res");
USEUNIT("..\..\design\JvProviderTreeListDsgnFrame.pas");
USEUNIT("..\..\design\JvProviderTreeListFrame.pas");
USEUNIT("..\..\design\JvStdToolbarDsgnFrame.pas");
USEUNIT("..\..\design\JvStringsForm.pas");
USEUNIT("..\..\design\JvBaseDlgEditor.pas");
USEUNIT("..\..\design\JvBaseDsgnForm.pas");
USEUNIT("..\..\design\JvBaseDsgnFrame.pas");
USEUNIT("..\..\design\JvBaseDsgnToolbarFrame.pas");
USEUNIT("..\..\design\JvColorEditor.pas");
USEUNIT("..\..\design\JvColorProviderDesignerForm.pas");
USEUNIT("..\..\design\JvColorProviderEditors.pas");
USEUNIT("..\..\design\JvCoreReg.pas");
USEUNIT("..\..\design\JvDataConsumerContextSelectForm.pas");
USEUNIT("..\..\design\JvDataConsumerItemSelectForm.pas");
USEUNIT("..\..\design\JvDataContextManagerForm.pas");
USEUNIT("..\..\design\JvDataProviderDesignerForm.pas");
USEUNIT("..\..\design\JvDataProviderEditors.pas");
USEUNIT("..\..\design\JvDataProviderItemDesign.pas");
USEUNIT("..\..\design\JvDateTimeForm.pas");
USEUNIT("..\..\design\JvDesignerUtils.pas");
USEUNIT("..\..\design\JvDsgnConsts.pas");
USEUNIT("..\..\design\JvDsgnEditors.pas");
USEUNIT("..\..\design\JvIDEZoom.pas");
USEUNIT("..\..\design\JvJVCLAboutEditor.pas");
USEUNIT("..\..\design\JvPaintBoxEditor.pas");
USEUNIT("..\..\design\JvProviderToolbarFrame.pas");
USEUNIT("..\..\design\JvDsgnTypes.pas");
USEUNIT("..\..\design\JvColorProviderDsgnTreeFrame.pas");
USEUNIT("..\..\design\JvColorProviderAddDialogForm.pas");
USEUNIT("..\..\design\JvActnResForm.pas");
USEUNIT("..\..\design\JvBackgroundEditors.pas");
USEUNIT("..\..\design\JvBackgroundEditForm.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("dclstd50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("CJCL50.bpi");
USEPACKAGE("vclx50.bpi");
USEPACKAGE("vcl50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

