//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvDotNetCtrls-D.xml)
            
     Last generated: 01-03-2006  08:42:36 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvDotNetCtrlsC5D.res");
USEUNIT("..\..\design\JvDotNetCtrlsReg.pas");
USEPACKAGE("JvCoreC5D.bpi");
USEPACKAGE("JvDotNetCtrlsC5R.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vclx50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

