//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvInterpreter-R.xml)
            
     Last generated: 21-02-2006  19:30:36 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvInterpreterC5R.res");
USEUNIT("..\..\run\JvInterpreterParser.pas");
USEUNIT("..\..\run\JvInterpreter.pas");
USEUNIT("..\..\run\JvInterpreter_all.pas");
USEUNIT("..\..\run\JvInterpreter_Buttons.pas");
USEUNIT("..\..\run\JvInterpreter_Classes.pas");
USEUNIT("..\..\run\JvInterpreter_ComCtrls.pas");
USEUNIT("..\..\run\JvInterpreter_Contnrs.pas");
USEUNIT("..\..\run\JvInterpreter_Controls.pas");
USEUNIT("..\..\run\JvInterpreter_Db.pas");
USEUNIT("..\..\run\JvInterpreter_DbCtrls.pas");
USEUNIT("..\..\run\JvInterpreter_DbGrids.pas");
USEUNIT("..\..\run\JvInterpreter_DBTables.pas");
USEUNIT("..\..\run\JvInterpreter_Dialogs.pas");
USEUNIT("..\..\run\JvInterpreter_ExtCtrls.pas");
USEUNIT("..\..\run\JvInterpreter_Forms.pas");
USEUNIT("..\..\run\JvInterpreter_Graphics.pas");
USEUNIT("..\..\run\JvInterpreter_Grids.pas");
USEUNIT("..\..\run\JvInterpreter_JvEditor.pas");
USEUNIT("..\..\run\JvInterpreter_JvInterpreter.pas");
USEUNIT("..\..\run\JvInterpreter_JvUtils.pas");
USEUNIT("..\..\run\JvInterpreter_Menus.pas");
USEUNIT("..\..\run\JvInterpreter_StdCtrls.pas");
USEUNIT("..\..\run\JvInterpreter_System.pas");
USEUNIT("..\..\run\JvInterpreter_SysUtils.pas");
USEUNIT("..\..\run\JvInterpreter_Types.pas");
USEUNIT("..\..\run\JvInterpreter_Windows.pas");
USEUNIT("..\..\run\JvInterpreterConst.pas");
USEUNIT("..\..\run\JvInterpreterFm.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JvCustomC5R.bpi");
USEPACKAGE("JvSystemC5R.bpi");
USEPACKAGE("JvStdCtrlsC5R.bpi");
USEPACKAGE("JCLC50.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vclx50.bpi");
USEPACKAGE("vclbde50.bpi");
USEPACKAGE("vcldb50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

