//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvPageComps-D.xml)
            
     Last generated: 01-03-2006  08:42:37 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvPageCompsC5D.res");
USEUNIT("..\..\design\JvPageLinkEditorForm.pas");
USEUNIT("..\..\design\JvPageListTreeViewReg.pas");
USEUNIT("..\..\design\JvTreeItemsEditorForm.pas");
USEUNIT("..\..\design\JvPageListEditorForm.pas");
USEUNIT("..\..\design\JvPageListEditors.pas");
USEUNIT("..\..\design\JvNavPaneEditors.pas");
USEPACKAGE("JvPageCompsC5R.bpi");
USEPACKAGE("JvCoreC5D.bpi");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dclstd50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

