//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvXPCtrls-R.xml)
            
     Last generated: 03-09-2004  16:23:25 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvXPCtrlsC5R.res");
USEUNIT("..\..\run\JvXPBar.pas");
USEUNIT("..\..\run\JvXPContainer.pas");
USEUNIT("..\..\run\JvXPCore.pas");
USEUNIT("..\..\run\JvXPCoreUtils.pas");
USEUNIT("..\..\run\JvXPButtons.pas");
USEUNIT("..\..\run\JvXPCheckCtrls.pas");
USEUNIT("..\..\run\JvXPProgressBar.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JvStdCtrlC5R.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vclx50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

