brc32 JvAppFrmReg.rc -r -fo..\Resources\JvAppFrmReg.dcr
brc32 JvBDEReg.rc -r -fo..\Resources\JvBDEReg.dcr
brc32 JvCmpReg.rc -r -fo..\Resources\JvCmpReg.dcr
brc32 JvCustomReg.rc -r -fo..\Resources\JvCustomReg.dcr
brc32 JvCoreReg.rc -r -fo..\Resources\JvCoreReg.dcr
brc32 JvCryptReg.rc -r -fo..\Resources\JvCryptReg.dcr
brc32 JvCtrlsReg.rc -r -fo..\Resources\JvCtrlsReg.dcr
brc32 JvDBReg.rc -r -fo..\Resources\JvDBReg.dcr
brc32 JvDlgsReg.rc -r -fo..\Resources\JvDlgsReg.dcr
brc32 JvInterpreterReg.rc -r -fo..\Resources\JvInterpreterReg.dcr
brc32 JvMMReg.rc -r -fo..\Resources\JvMMReg.dcr
brc32 JvNetReg.rc -r -fo..\Resources\JvNetReg.dcr
brc32 JvStdCtrlsReg.rc -r -fo..\Resources\JvStdCtrlsReg.dcr
brc32 JvSystemReg.rc -r -fo..\Resources\JvSystemReg.dcr