@echo off
brc32 JvBaseEdits.rc -r -fo..\Resources\JvBaseEdits.res
brc32 JvCalc.rc -r -fo..\Resources\JvCalc.res
brc32 JvCheckmarks.rc -r -fo..\Resources\JvCheckmarks.res
brc32 JvColorCombo.rc -r -fo..\Resources\JvColorCombo.res
brc32 JvComponentPanel.rc -r -fo..\Resources\JvComponentPanel.res
brc32 JvConsts.rc -r -fo..\Resources\JvConsts.res
brc32 JvCSVBase.rc -r -fo..\Resources\JvCSVBase.res
brc32 JvCtrls.rc -r -fo..\Resources\JvCtrls.res
brc32 JvDBCtrl.rc -r -fo..\Resources\JvDBCtrl.res
brc32 JvDice.rc -r -fo..\Resources\JvDice.res
brc32 JvEnterTab.rc -r -fo..\Resources\JvEnterTab.res
brc32 JvErrorIndicator.rc -r -fo..\Resources\JvErrorIndicator.res
brc32 JvGammaPanel.rc -r -fo..\Resources\JvGammaPanel.res
brc32 JvgButton.rc -r -fo..\Resources\JvgButton.res
brc32 JvgCaption.rc -r -fo..\Resources\JvgCaption.res
brc32 JvgCheckBox.rc -r -fo..\Resources\JvgCheckBox.res
brc32 JvgHint.rc -r -fo..\Resources\JvgHint.res
brc32 JvgLabelEditorForm.rc -r -fo..\Resources\JvgLabelEditorForm.res
brc32 JvgTreeView.rc -r -fo..\Resources\JvgTreeView.res
brc32 JvLED.rc -r -fo..\Resources\JvLED.res
brc32 JvLinkLabel.rc -r -fo..\Resources\JvLinkLabel.res
brc32 JvOutlookBar.rc -r -fo..\Resources\JvOutlookBar.res
brc32 JvPageSetupTitledEng.rc -r -fo..\Resources\JvPageSetupTitledEng.res
brc32 JvPageSetupTitledRus.rc -r -fo..\Resources\JvPageSetupTitledRus.res
brc32 JvPickDate.rc -r -fo..\Resources\JvPickDate.res
brc32 JvPluginWiz.rc -r -fo..\Resources\JvPluginWiz.res
brc32 JvRegistryTreeView.rc -r -fo..\Resources\JvRegistryTreeView.res
brc32 JvScrollMax.rc -r -fo..\Resources\JvScrollMax.res
brc32 JvSegmentedLEDDisplay.rc -r -fo..\Resources\JvSegmentedLEDDisplay.res
brc32 JvSimImages.rc -r -fo..\Resources\JvSimImages.res
brc32 JvSlider.rc -r -fo..\Resources\JvSlider.res
brc32 JvSpin.rc -r -fo..\Resources\JvSpin.res
brc32 JvSwitch.rc -r -fo..\Resources\JvSwitch.res
brc32 JvTimeLine.rc -r -fo..\Resources\JvTimeLine.res
brc32 JvTipOfDay.rc -r -fo..\Resources\JvTipOfDay.res
brc32 JvTMTimeLine.rc -r -fo..\Resources\JvTMTimeLine.res
brc32 JvToolEdit.rc -r -fo..\Resources\JvToolEdit.res
brc32 JvWinampLabel.rc -r -fo..\Resources\JvWinampLabel.res
brc32 JvxCheckListBox.rc -r -fo..\Resources\JvxCheckListBox.res
brc32 JvxSlider.rc -r -fo..\Resources\JvxSlider.res
