//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvAppFrm-D.xml)
            
     Last generated: 13-12-2003  05:58:44 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\design\JvGradientCaptionForm.pas", Jvgradientcaptionform, GradCaptionsEditor); 
USEFORMNS("..\..\run\JvWallpaperEditForm.pas", Jvwallpapereditform, FoWallpaperChooser); 
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

