//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvBDE-R.xml)
            
     Last generated: 29-11-2003  13:25:41 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\run\JvBDECheckPasswordForm.pas", Jvbdecheckpasswordform, JvChPswdForm); 
USEFORMNS("..\..\run\JvBDEExceptionForm.pas", Jvbdeexceptionform, JvBdeErrorDlg); 
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

