//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvCoreC6D.xml)
            
     Last generated: 16-11-2003  11:50:56 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\design\JvProviderTreeListDsgnFrame.pas", Jvprovidertreelistdsgnframe, fmeJvProviderTreeListDsgn); /* TFrame: File Type */
USEFORMNS("..\..\design\JvProviderTreeListFrame.pas", Jvprovidertreelistframe, fmeJvProviderTreeList); /* TFrame: File Type */
USEFORMNS("..\..\design\JvStdToolbarDsgnFrame.pas", Jvstdtoolbardsgnframe, fmeJvStdToolbarDesign); /* TFrame: File Type */
USEFORMNS("..\..\design\JvStringsForm.pas", Jvstringsform, JvStrEditDlg); /* : File Type */
USEFORMNS("..\..\design\JvBaseDsgnForm.pas", Jvbasedsgnform, JvBaseDesign); /* : File Type */
USEFORMNS("..\..\design\JvBaseDsgnFrame.pas", Jvbasedsgnframe, fmeJvBaseDesign); /* TFrame: File Type */
USEFORMNS("..\..\design\JvBaseDsgnToolbarFrame.pas", Jvbasedsgntoolbarframe, fmeJvBaseToolbarDesign); /* TFrame: File Type */
USEFORMNS("..\..\design\JvColorProviderDesignerForm.pas", Jvcolorproviderdesignerform, frmJvColorProviderDesigner); /* : File Type */
USEFORMNS("..\..\design\JvDataConsumerContextSelectForm.pas", Jvdataconsumercontextselectform, frmDataConsumerContextSelect); /* : File Type */
USEFORMNS("..\..\design\JvDataConsumerItemSelectForm.pas", Jvdataconsumeritemselectform, frmJvDataConsumerItemSelect); /* : File Type */
USEFORMNS("..\..\design\JvDataContextManagerForm.pas", Jvdatacontextmanagerform, frmJvDataContextManager); /* : File Type */
USEFORMNS("..\..\design\JvDataProviderDesignerForm.pas", Jvdataproviderdesignerform, frmDataProviderDesigner); /* : File Type */
USEFORMNS("..\..\design\JvDateTimeForm.pas", Jvdatetimeform, frmSelectDateTimeDlg); /* : File Type */
USEFORMNS("..\..\design\JvProviderToolbarFrame.pas", Jvprovidertoolbarframe, fmeJvProviderToolbar); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

