//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvDB-R.xml)
            
     Last generated: 04-12-2003  12:48:26 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\run\JvDBQueryParamsForm.pas", Jvdbqueryparamsform, JvQueryParamsDialog); 
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

