//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvDlgsC6R.xml)
            
     Last generated: 16-11-2003  11:27:59 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\run\JvDualListForm.pas", Jvduallistform, JvDualListForm); /* : File Type */
USEFORMNS("..\..\run\JvExceptionForm.pas", Jvexceptionform, JvErrorDialog); /* : File Type */
USEFORMNS("..\..\run\JvImageForm.pas", Jvimageform, FormImg); /* : File Type */
USEFORMNS("..\..\run\JvLoginForm.pas", Jvloginform, JvLoginForm); /* : File Type */
USEFORMNS("..\..\run\JvProgressForm.pas", Jvprogressform, frmProgress); /* : File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

