//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvBands-R.xml)
            
     Last generated: 01-03-2006  08:42:36 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvBandsC5R.res");
USEUNIT("..\..\run\JvBandForms.pas");
USEUNIT("..\..\run\JvBandObject.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcl50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

