//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvEDI-R.xml)
            
     Last generated: 19-10-2005  18:14:52 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvEDIC5R.res");
USEUNIT("..\..\run\JvEDIDBBuffering.pas");
USEPACKAGE("JvCoreC5R.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcldb50.bpi");
USEPACKAGE("vcl50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

