//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvStdCtrls-D.xml)
            
     Last generated: 19-10-2005  19:43:48 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JvStdCtrlsC5D.res");
USEUNIT("..\..\design\JvCheckedItemsForm.pas");
USEUNIT("..\..\design\JvProgressEditor.pas");
USEUNIT("..\..\design\JvStdCtrlsReg.pas");
USEPACKAGE("JvCoreC5D.bpi");
USEPACKAGE("JvStdCtrlsC5R.bpi");
USEPACKAGE("JvCtrlsC5R.bpi");
USEPACKAGE("JvSystemC5D.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dclstd50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

