@echo off
brc32 JvAppFrmReg.rc -r -fo..\Resources\JvAppFrmReg.dcr
brc32 JvBDEReg.rc -r -fo..\Resources\JvBDEReg.dcr
brc32 JvCmpReg.rc -r -fo..\Resources\JvCmpReg.dcr
brc32 JvCustomReg.rc -r -fo..\Resources\JvCustomReg.dcr
brc32 JvCoreReg.rc -r -fo..\Resources\JvCoreReg.dcr
brc32 JvCryptReg.rc -r -fo..\Resources\JvCryptReg.dcr
brc32 JvCtrlsReg.rc -r -fo..\Resources\JvCtrlsReg.dcr
brc32 JvDBReg.rc -r -fo..\Resources\JvDBReg.dcr
brc32 JvDlgsReg.rc -r -fo..\Resources\JvDlgsReg.dcr
brc32 JvInterpreterReg.rc -r -fo..\Resources\JvInterpreterReg.dcr
brc32 JvHMIReg.rc -r -fo..\Resources\JvHMIReg.dcr
brc32 JvMMReg.rc -r -fo..\Resources\JvMMReg.dcr
brc32 JvNetReg.rc -r -fo..\Resources\JvNetReg.dcr
brc32 JvStdCtrlsReg.rc -r -fo..\Resources\JvStdCtrlsReg.dcr
brc32 JvSystemReg.rc -r -fo..\Resources\JvSystemReg.dcr
brc32 JvPluginReg.rc -r -fo..\Resources\JvPluginReg.dcr
brc32 JvJansReg.rc -r -fo..\Resources\JvJansReg.dcr
brc32 JvGlobusReg.rc -r -fo..\Resources\JvGlobusReg.dcr
brc32 JvUIBReg.rc -r -fo..\Resources\JvUIBReg.dcr
brc32 JvPageListTreeViewReg.rc -r -fo..\Resources\JvPageListTreeViewReg.dcr
brc32 JvPreviewReg.rc -r -fo..\Resources\JvPreviewReg.dcr
brc32 JvValidatorsReg.rc -r -fo..\Resources\JvValidatorsReg.dcr
brc32 JvWizardReg.rc -r -fo..\Resources\JvWizardReg.dcr
brc32 JvTimeFrameWorkReg.rc -r -fo..\Resources\JvTimeFrameWorkReg.dcr
brc32 JvManagedThreadsReg.rc -r -fo..\Resources\JvManagedThreadsReg.dcr
brc32 JvXPCtrlsReg.rc -r -fo..\Resources\JvXPCtrlsReg.dcr
brc32 JvDotNetCtrlsReg.rc -r -fo..\Resources\JvDotNetCtrlsReg.dcr
