//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvDlgs-R.xml)
            
     Last generated: 03-02-2004  01:13:12 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\run\JvDualListForm.pas", Jvduallistform, JvDualListForm); 
USEFORMNS("..\..\run\JvExceptionForm.pas", Jvexceptionform, JvErrorDialog); 
USEFORMNS("..\..\run\JvLoginForm.pas", Jvloginform, JvLoginForm); 
USEFORMNS("..\..\run\JvProgressForm.pas", Jvprogressform, frmProgress); 
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

