//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvWizard-D.xml)
            
     Last generated: 11-06-2009  10:14:41 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\design\JvWizardEditorForm.pas", Jvwizardeditorform, JvWizardPageListEditor); 
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

