<?xml version="1.0" encoding="ISO-8859-1" ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <title>Hospital v1.0::Medical Stock</title>
 <link rel="stylesheet" href="styles.css" type="text/css" />
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>

<div class="Main">

<div class="Intro"><img src="images/top.png" alt="" /></div>

<table class="Main" cellspacing="0" cellpadding="0">
<tr><td class="Menu" valign="top">
 <a href="index.xhs">Index</a>

 <br /><b>Boxes</b>
 <br />&nbsp;<a href="box_loan.xhs">Emprunt</a>
 <br />&nbsp;<a href="box_return.xhs">Retour</a>
 <br />&nbsp;<a href="box_manage.xhs">Liste</a>
 <br />&nbsp;<a href="box_create.xhs">Ajouter</a>

 <br /><b>Loans</b>
 <br />&nbsp;<a href="loans.xhs">Liste</a>

 <br /><b>Clients</b>
 <br />&nbsp;<a href="clients.xhs">Liste</a>
 <br />&nbsp;<a href="client_create.xhs">Ajouter</a>

 <br /><b>Instruments</b>
 <br />&nbsp;<a href="items.xhs">Liste</a>
 <br />&nbsp;<a href="item_create.xhs">Ajouter</a>

 <br /><b>Users</b>
 <br />&nbsp;<a href="users.xhs">Liste</a>
 <br />&nbsp;<a href="user_create.xhs">Ajouter</a>

</td><td valign="top" class="Text">
