//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JvDBC6D.xml)
            
     Last generated: 16-11-2003  11:27:59 UTC     
-----------------------------------------------------------------------------
*/

#include <basepch.h>
#pragma hdrstop
USEFORMNS("..\..\design\JvSelectDataSetForm.pas", Jvselectdatasetform, JvSelectDataSetForm); /* : File Type */
USEFORMNS("..\..\design\JvCsvDataForm.pas", Jvcsvdataform, JvCsvDefStrDialog); /* : File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

